# Generated by Django 4.0.4 on 2022-04-29 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='user',
            new_name='customer',
        ),
    ]
