# Generated by Django 4.0.4 on 2022-04-29 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_user_order_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='customer',
            new_name='user',
        ),
    ]
