# Generated by Django 4.0.4 on 2022-04-30 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_order_user_remove_shippingaddress_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer',
            new_name='customer_id',
        ),
    ]
